import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#f7f8f5",
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f7f8f5",
  },
  loadingText: {
    color: "#475569",
    marginTop: 12,
    fontWeight: "700",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingBottom: 10,
    paddingTop: 10,
  },
  headerIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  searchInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dbe5e1",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    color: "#13201f",
    fontSize: 14,
    outlineStyle: "none",
  },
  emptySearchText: {
    color: "#64748b",
    fontWeight: "700",
    textAlign: "center",
    paddingVertical: 22,
  },
  errorInline: {
    color: "#b91c1c",
    fontWeight: "700",
    marginBottom: 12,
  },
  scoreLegend: {
    color: "#64748b",
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 12,
  },
  restaurantMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 4,
  },
  priceBadge: {
    color: "#0f766e",
    backgroundColor: "#e0f2ef",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: "800",
  },
  greeting: {
    color: "#64748b",
    fontSize: 13,
    fontWeight: "700",
  },
  userName: {
    color: "#13201f",
    fontSize: 23,
    fontWeight: "800",
  },
  roleSwitch: {
    borderRadius: 999,
    backgroundColor: "#0f766e",
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  roleSwitchText: {
    color: "#ffffff",
    fontWeight: "800",
  },
  content: {
    flex: 1,
  },
  flex: {
    flex: 1,
  },
  stack: {
    gap: 14,
  },
  listContent: {
    gap: 14,
    padding: 16,
    paddingBottom: 98,
  },
  innerListContent: {
    gap: 14,
    padding: 16,
    paddingBottom: 112,
  },
  heroCard: {
    borderRadius: 8,
    backgroundColor: "#123331",
    padding: 18,
  },
  heroKicker: {
    color: "#b8d9d4",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  heroText: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "800",
    lineHeight: 27,
    marginTop: 8,
  },
  heroStats: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  miniStat: {
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  miniStatValue: {
    color: "#ffffff",
    fontSize: 17,
    fontWeight: "900",
  },
  miniStatLabel: {
    color: "#cde4e0",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    color: "#13201f",
    fontSize: 16,
    fontWeight: "900",
  },
  linkText: {
    color: "#0f766e",
    fontSize: 13,
    fontWeight: "900",
  },
  card: {
    borderRadius: 8,
    backgroundColor: "#ffffff",
    padding: 15,
    shadowColor: "#0f172a",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  cardTitle: {
    color: "#13201f",
    fontSize: 16,
    fontWeight: "800",
  },
  cardMeta: {
    color: "#64748b",
    fontSize: 13,
    marginTop: 4,
  },
  cardBody: {
    color: "#334155",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  cardFooter: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 12,
  },
  achievementLabel: {
    alignSelf: "flex-start",
    borderRadius: 999,
    backgroundColor: "#ffedd5",
    color: "#9a3412",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  scoreBadge: {
    minWidth: 40,
    borderRadius: 8,
    backgroundColor: "#dcfce7",
    color: "#166534",
    fontSize: 14,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 7,
    textAlign: "center",
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
  },
  profileHero: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 20,
    alignItems: "center",
    marginBottom: 4,
  },
  profileAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#0f766e",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  profileAvatarText: {
    color: "#ffffff",
    fontSize: 28,
    fontWeight: "800",
  },
  profileName: {
    fontSize: 22,
    fontWeight: "800",
    color: "#0f172a",
  },
  profileRole: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0f766e",
    marginTop: 4,
  },
  profileGoal: {
    fontSize: 14,
    color: "#475569",
    fontStyle: "italic",
    textAlign: "center",
    marginTop: 12,
  },
  statCard: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: "#ffffff",
    padding: 14,
  },
  statValue: {
    color: "#0f766e",
    fontSize: 22,
    fontWeight: "900",
  },
  statLabel: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 4,
  },
  progressTrack: {
    height: 9,
    borderRadius: 999,
    backgroundColor: "#e2e8f0",
    marginTop: 14,
    overflow: "hidden",
  },
  progressFill: {
    height: 9,
    borderRadius: 999,
    backgroundColor: "#0f766e",
  },
  segmented: {
    flexDirection: "row",
    borderRadius: 8,
    backgroundColor: "#e2e8f0",
    marginTop: 14,
    padding: 4,
  },
  segment: {
    flex: 1,
    alignItems: "center",
    borderRadius: 6,
    paddingVertical: 9,
  },
  segmentActive: {
    backgroundColor: "#ffffff",
  },
  segmentText: {
    color: "#64748b",
    fontWeight: "800",
  },
  segmentTextActive: {
    color: "#0f766e",
  },
  textArea: {
    minHeight: 102,
    borderRadius: 8,
    backgroundColor: "#f8fafc",
    color: "#13201f",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 14,
    padding: 12,
    textAlignVertical: "top",
  },
  input: {
    borderRadius: 8,
    backgroundColor: "#f8fafc",
    color: "#13201f",
    fontSize: 15,
    marginTop: 14,
    padding: 12,
  },
  primaryButton: {
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: "#0f766e",
    marginTop: 14,
    paddingVertical: 13,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  secondaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 8,
    backgroundColor: "#ecfdf5",
    marginTop: 12,
    paddingVertical: 9,
  },
  secondaryButtonText: {
    color: "#0f766e",
    fontSize: 13,
    fontWeight: "900",
  },
  iconButton: {
    alignItems: "center",
    justifyContent: "center",
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: "#0f766e",
  },
  friendRail: {
    gap: 12,
    paddingRight: 16,
  },
  friendCard: {
    width: 210,
    borderRadius: 8,
    backgroundColor: "#ffffff",
    padding: 14,
  },
  groupCard: {
    minHeight: 200,
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    backgroundColor: "#f1f5f9",
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  actionButtonActive: {
    backgroundColor: "#ffe4e6",
  },
  actionText: {
    color: "#64748b",
    fontSize: 13,
    fontWeight: "900",
  },
  actionTextActive: {
    color: "#be123c",
  },
  commentBubble: {
    borderLeftWidth: 3,
    borderLeftColor: "#ccfbf1",
    marginTop: 12,
    paddingLeft: 10,
  },
  commentAuthor: {
    color: "#0f766e",
    fontSize: 12,
    fontWeight: "900",
  },
  commentText: {
    color: "#334155",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 2,
  },
  commentComposer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 12,
  },
  commentInput: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: "#f8fafc",
    color: "#13201f",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  smallSendButton: {
    alignItems: "center",
    justifyContent: "center",
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: "#0f766e",
  },
  servicesLayout: {
    flex: 1,
  },
  serviceTabs: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 16,
    paddingBottom: 6,
  },
  serviceTab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 8,
    backgroundColor: "#e2e8f0",
    paddingVertical: 10,
  },
  serviceTabActive: {
    backgroundColor: "#ffffff",
  },
  serviceTabText: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "900",
  },
  serviceTabTextActive: {
    color: "#0f766e",
  },
  messageLayout: {
    flex: 1,
  },
  conversationRail: {
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  conversationHeader: {
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  newConvButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#0f766e",
    alignSelf: "flex-start",
  },
  newConvButtonText: {
    color: "#0f766e",
    fontWeight: "700",
    fontSize: 13,
  },
  newConvPanel: {
    backgroundColor: "#ffffff",
    marginHorizontal: 16,
    marginTop: 10,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    gap: 10,
  },
  newConvPanelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  newConvFriendRow: {
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
  },
  conversationChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 8,
    backgroundColor: "#ffffff",
    height: 44,
    paddingHorizontal: 12,
  },
  conversationChipActive: {
    backgroundColor: "#0f766e",
  },
  conversationName: {
    color: "#475569",
    fontSize: 13,
    fontWeight: "900",
  },
  conversationNameActive: {
    color: "#ffffff",
  },
  unreadBadge: {
    minWidth: 24,
    borderRadius: 999,
    backgroundColor: "#f97316",
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 7,
    paddingVertical: 3,
    textAlign: "center",
  },
  threadContent: {
    gap: 10,
    paddingHorizontal: 16,
    paddingBottom: 14,
  },
  messageBubble: {
    alignSelf: "flex-start",
    maxWidth: "82%",
    borderRadius: 8,
    backgroundColor: "#ffffff",
    padding: 12,
  },
  messageBubbleMine: {
    alignSelf: "flex-end",
    backgroundColor: "#0f766e",
  },
  messageText: {
    color: "#334155",
    fontSize: 14,
    lineHeight: 20,
  },
  messageTextMine: {
    color: "#ffffff",
  },
  messageTime: {
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 6,
  },
  messageTimeMine: {
    color: "#ccfbf1",
  },
  messageComposer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    backgroundColor: "#f7f8f5",
    padding: 16,
    paddingBottom: 100,
  },
  messageInput: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: "#ffffff",
    color: "#13201f",
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  sendButton: {
    alignItems: "center",
    justifyContent: "center",
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: "#0f766e",
  },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 10,
  },
  settingText: {
    flex: 1,
  },
  settingTitle: {
    color: "#13201f",
    fontSize: 15,
    fontWeight: "900",
  },
  tabBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-around",
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    backgroundColor: "#ffffff",
    paddingBottom: 10,
    paddingTop: 9,
  },
  tabButton: {
    alignItems: "center",
    gap: 4,
    minWidth: 56,
  },
  tabLabel: {
    color: "#64748b",
    fontSize: 10,
    fontWeight: "800",
  },
  tabLabelActive: {
    color: "#0f766e",
  },
  composerActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 14,
  },
  composerIconButton: {
    alignItems: "center",
    justifyContent: "center",
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#ecfdf5",
  },
  imagePreviewContainer: {
    position: "relative",
    marginTop: 14,
    borderRadius: 12,
    overflow: "hidden",
  },
  imagePreview: {
    width: "100%",
    height: 200,
    borderRadius: 12,
  },
  clearImageBtn: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    borderRadius: 999,
    padding: 6,
  },
  feedImage: {
    width: "100%",
    aspectRatio: 4 / 3,
    borderRadius: 16,
    marginTop: 12,
  },
  logoutButton: {
    marginTop: 18,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 10,
    backgroundColor: "#fef2f2",
    borderColor: "#fecaca",
    borderWidth: 1,
    alignSelf: "center",
  },
  logoutButtonText: {
    color: "#b91c1c",
    fontWeight: "700",
    fontSize: 13,
  },
});
